service: serverless-numpy

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  deploymentMethod: direct

functions:
  hello:
    handler: handler.hello

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

